#Netskope REST API Access
Netskope_API:
#tenant name don't forget ".eu" or ".de", check the console url
  nsurl: "mytenant.goskope.com"
  nstoken: "1234"
#leave proxy empty if not needed, format is http://user:password@192.168.1.1:3128/
  proxy:

#Local folder
download_location: "ns_transactionlogs"

#Select mode for existing files in destination location: replace, skip, retry
# "replace": overwrite any existing file with new ones
# "retry": overwrite if size is different
# "skip": skip all existing file, even if the file has different size
existing_file: "retry"

# number of previous hours to retrieve  (0 to retrieve all)
timeperiod: 0

#loglevel, level=0 to disable, 1=new files only, 2=all files, 3=all files+all objects excluded by timeperiod
Log:
  level: 1
  file: ns_transactionlogs.log
